### PR TITLE
Closes #86 identifies and resolves the `GroupLabelKey` error

### LINKED ISSUE #86: Bugfix: `GroupLabelKey` not found in new Flags Changed section of gsm.kri report
## Current Behavior

Error pops up when running Report_KRI Rmd in the new Flags Changes section of the report.

Image

## Steps to Reproduce

1.
2.
3.
4.

### PR DESCRIPTION
**Pull request by zdz2101**

### CODE REVIEW

File: R/Report_Setup.R [hunk 1]
```diff
@@ -32,6 +32,14 @@ Report_Setup <- function(dfGroups = NULL, dfMetrics = NULL, dfResults = NULL) {
     output$GroupLevel <- ""
   }
 
+  if(output$GroupLevel == "Site"){
+    output$GroupLabelKey <- "InvestigatorLastName"
+  } else if(output$GroupLevel == "Country"){
+    output$GroupLabelKey <- "GroupID"
```
Comment (zdz2101) [inline R/Report_Setup.R:38]: This fixes our `setup` object to grab the "correct" column at line 145 of the RMD code for the flag change html @lauramaxwell @jwildfire

**Review by lauramaxwell — APPROVED** [review]
Looks great! thanks for the quick turnaround. Added a couple small edits to the example script to align it with changes made to the file in gsm.core.
